<?php
/**
 * Created by PhpStorm.
 * User: Jason
 * Date: 2017/7/3
 * Time: 20:58
 */
namespace  app\admin\controller;

use app\common\controller\AdminCommon;
use think\Db;

class Index extends AdminCommon{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $db_version = Db::query('SELECT VERSION() AS ver');
        $config     = [
            'document_root'   => $_SERVER['DOCUMENT_ROOT'],
            'server_os'   => PHP_OS,
            'server_port'     => $_SERVER['SERVER_PORT'],
            'server_soft'     => $_SERVER['SERVER_SOFTWARE'],
            'php_version'     => PHP_VERSION,
            'mysql_version'   => $db_version[0]['ver'],
            'max_upload_size' => ini_get('upload_max_filesize'),
            'post_size'       => ini_get('post_max_size')
        ];
        return $this->fetch('index', ['config' => $config]);
    }
}