<?php
/**
 * Created by PhpStorm.
 * User: Jason
 * Date: 2017/8/30
 * Time: 7:56
 */
namespace app\common\controller;

use think\Controller;
use think\Session;
use think\Request;
use think\Response;

class ApiCommon extends Controller {

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!Session::has('admin_id')) {
            $result = [
                'error'   => 1,
                'message' => '未登录'
            ];
            exit($this->response($result)->send());
        }
    }

    /**
     * 输出返回数据
     */
    public function response($result, $type = 'json')
    {
        return Response::create($result, $type)->code(200);
    }
}