<?php
/**
 * Created by PhpStorm.
 * User: Jason
 * Date: 2017/7/29
 * Time: 10:52
 */
namespace app\common\controller;

use think\Controller;
use think\Db;
use think\Cache;

/*
 * 前台公用控制器
 */
class IndexCommon extends Controller{

    protected function _initialize()
    {
        $this->getNav();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    protected function getNav()
    {
        $nav = Db::name('navigation')->where('status', 1)->order('sort desc')->select();
        $navList= build_tree($nav, 0);

        $this->assign('navList', $navList);
    }

}