<?php
/**
 * Created by PhpStorm.
 * User: Jason
 * Date: 2017/9/2
 * Time: 17:01
 */
namespace app\api\controller;

use think\Controller;

class Webhook extends Controller{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * url: /api/webhook/update
     */
    public function update()
    {
        error_reporting(1);
        $target = '/home/wwwroot/www.totoroc.cn'; // 生产环境web目录
        $wwwUser = 'www';
        $wwwGroup = 'www';
        $json = json_decode(file_get_contents('php://input'), true);

        $cmds = array(
            "cd $target && git pull origin develop",
            "chown -R {$wwwUser}:{$wwwGroup} $target/"
        );
        foreach ($cmds as $cmd) {
            exec($cmd);

            $res_log = '-------------------------'.PHP_EOL;

            $res_log .= '在 ' . date('Y-m-d H:s:i') . ' 执行了 ' . $cmd;

            file_put_contents("./git-webhook.txt", $res_log, FILE_APPEND);
        }
    }
}