<?php
/**
 * Created by PhpStorm.
 * User: Jason
 * Date: 2017/9/2
 * Time: 17:01
 */
namespace app\api\controller;

use think\Controller;

class Webhook extends Controller{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * url: /api/webhook/update
     */
    public function update()
    {

    }
}